name: dino_wm
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.15.3=hb03c661_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he90730b_1
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h24cb091_1
  - ffmpeg=8.0.1=gpl_hf567e27_909
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - glslang=16.1.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.11=h18acefa_1
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=12.3.0=h6083320_0
  - icu=78.2=h33c6efd_0
  - imageio=2.37.0=pyhfb79c49_0
  - intel-gmmlib=22.9.0=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.27.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libass=0.17.4=h96ad9f0_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h6548e54_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopenvino=2025.4.1=hb56ce9e_0
  - libopenvino-auto-batch-plugin=2025.4.1=hd85de46_0
  - libopenvino-auto-plugin=2025.4.1=hd85de46_0
  - libopenvino-hetero-plugin=2025.4.1=hd41364c_0
  - libopenvino-intel-cpu-plugin=2025.4.1=hb56ce9e_0
  - libopenvino-intel-gpu-plugin=2025.4.1=hb56ce9e_0
  - libopenvino-intel-npu-plugin=2025.4.1=hb56ce9e_0
  - libopenvino-ir-frontend=2025.4.1=hd41364c_0
  - libopenvino-onnx-frontend=2025.4.1=h1862bb8_0
  - libopenvino-paddle-frontend=2025.4.1=h1862bb8_0
  - libopenvino-pytorch-frontend=2025.4.1=hecca717_0
  - libopenvino-tensorflow-frontend=2025.4.1=h0767aad_0
  - libopenvino-tensorflow-lite-frontend=2025.4.1=hecca717_0
  - libopus=1.6.1=h280c20c_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.54=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_4
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc7d488a_2
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=258.3=h6569c3e_0
  - libtasn1=4.21.0=hb03c661_0
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.3=h6569c3e_0
  - libunistring=0.9.10=h7f98852_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.13=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.3=h5347b49_0
  - libva=2.23.0=he1eb515_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.15.2=hecca717_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mpg123=1.32.9=hc50e24c_0
  - ncurses=6.5=h2d0b736_3
  - nettle=3.10.1=h4a9d5aa_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - p11-kit=0.26.0=h3435931_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.47=haa7fec5_0
  - pillow=11.3.0=py39h15c0740_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a6aba3_3
  - python=3.9.19=h0755675_0_cpython
  - python_abi=3.9=8_cp39
  - readline=8.3=h853b02a_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.30=h3b84278_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.5=h3e344bc_0
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2025.4=hb700be7_0
  - svt-av1=3.1.2=hecca717_0
  - tbb=2022.3.0=hb700be7_2
  - tk=8.6.13=noxft_ha0e22de_103
  - tzdata=2025c=hc9c84f9_1
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.47=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.1.0
      - accelerate==0.26.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - array-record==0.5.1
      - asttokens==3.0.0
      - astunparse==1.6.3
      - attrs==23.2.0
      - bddl==1.0.1
      - beautifulsoup4==4.13.3
      - cachetools==5.3.3
      - certifi==2024.6.2
      - cffi==1.16.0
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - chex==0.1.85
      - click==8.1.7
      - cloudpickle==2.1.0
      - contextlib2==21.6.0
      - cycler==0.12.1
      - cython==0.29.37
      - d4rl==1.1
      - decorator==4.4.2
      - decord==0.6.0
      - distlib==0.3.8
      - distrax==0.1.5
      - dm-control==1.0.27
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - easydict==1.9
      - egl-probe==1.0.2
      - einops==0.4.1
      - etils==1.5.2
      - eval-type-backport==0.3.1
      - evdev==1.7.1
      - exceptiongroup==1.2.1
      - executing==2.2.0
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - filelock==3.14.0
      - flatbuffers==24.3.25
      - flax==0.7.5
      - fonttools==4.53.0
      - fsspec==2024.5.0
      - future==0.18.2
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - google-auth==2.29.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.64.0
      - gym==0.23.1
      - gym-notices==0.0.8
      - h5py==3.11.0
      - huggingface-hub==0.23.2
      - hydra-core==1.2.0
      - hydra-submitit-launcher==1.2.0
      - identify==2.5.36
      - idna==3.7
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - ipdb==0.13.13
      - ipython==8.18.1
      - jax==0.4.27
      - jaxlib==0.4.27
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupytext==1.16.2
      - keras==2.15.0
      - kiwisolver==1.4.5
      - labmaze==1.0.6
      - libclang==18.1.1
      - llvmlite==0.42.0
      - lxml==5.3.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.1
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.2.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.8
      - mujoco==3.2.7
      - mujoco-py==2.1.2.14
      - namex==0.1.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nodeenv==1.9.0
      - numba==0.59.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.590.44
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - nvitop==1.4.2
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.6.0.66
      - openexr==3.2.4
      - opt-einsum==3.3.0
      - optax==0.1.5
      - optree==0.18.0
      - orbax-checkpoint==0.4.4
      - packaging==24.0
      - parso==0.8.4
      - pathtools==0.1.2
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - plotly==5.22.0
      - pluggy==1.5.0
      - pre-commit==3.3.3
      - proglog==0.1.10
      - promise==2.3
      - prompt-toolkit==3.0.50
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pybind11==2.13.6
      - pybind11-global==2.13.6
      - pybullet==3.2.7
      - pycocotools==2.0.7
      - pycparser==2.22
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygame==2.5.2
      - pygments==2.18.0
      - pymunk==6.8.0
      - pynput==1.7.7
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - pytest==8.2.1
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pywavelets==1.6.0
      - pyyaml==6.0.1
      - referencing==0.35.1
      - regex==2024.5.15
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - robomimic==0.2.0
      - robosuite==1.4.1
      - rpds-py==0.18.1
      - rsa==4.9
      - safetensors==0.4.3
      - scikit-image==0.19.3
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - sentry-sdk==2.3.1
      - setproctitle==1.3.3
      - shapely==2.0.3
      - shortuuid==1.0.13
      - six==1.16.0
      - smmap==5.0.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - submitit==1.5.1
      - sympy==1.14.0
      - tenacity==8.3.0
      - termcolor==2.4.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2024.5.22
      - tokenizers==0.12.1
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.1
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.21.1
      - trimesh==4.4.0
      - triton==3.4.0
      - typeguard==2.13.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.2.1
      - virtualenv==20.26.2
      - wandb==0.24.0
      - wcwidth==0.2.13
      - werkzeug==3.0.3
      - wrapt==1.14.1
      - zipp==3.19.1
